/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer.window;

import javax.swing.JOptionPane;
import s_n.add.AddRelation;
import s_n.connection.Relationship;
import viewer.MethodImp;

/**
 *
 * @author Leo
 */
public class Menu5 extends javax.swing.JFrame {

	/**
	 * Creates new form Menu5
	 */
	public Menu5() {
		initComponents();
		new MethodImp().init(this, lb1.getText().trim());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lb1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		name1 = new javax.swing.JTextField();
		name2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lb1.setText("Check Connection of Two");

		jLabel2.setText("First person's first name:");

		jLabel3.setText("Second person's first name:");

		jButton1.setText("Check");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Cancle");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(396, 396, 396).addComponent(lb1))
						.addGroup(layout.createSequentialGroup().addGap(168, 168, 168)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addComponent(jButton1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton2))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42,
														Short.MAX_VALUE)
												.addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 292,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 292,
														javax.swing.GroupLayout.PREFERRED_SIZE)))))
				.addGap(300, 300, 300)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(66, 66, 66).addComponent(lb1).addGap(100, 100, 100)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(87, 87, 87)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1).addComponent(jButton2))
						.addGap(171, 171, 171)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		new MethodImp().goM(this);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		if (new MethodImp().checkStr(name1.getText().trim()) && new MethodImp().checkStr(name2.getText().trim())) {
			String name1 = this.name1.getText().trim();
			String name2 = this.name2.getText().trim();
			String outP = "0";
			for (int i = 0; i <= AddRelation.numre; i++) {
		
					if (AddRelation.re[i] instanceof Relationship) {
						
						outP = AddRelation.re[i].friend(name1, name2);
						
						if (outP.equals("4")) {
							JOptionPane.showMessageDialog(this, name1 + " and " + name2 + " are couple");
							break;
						} else if (outP.equals("1")) {
							JOptionPane.showMessageDialog(this, name1 + " and " + name2 + " are friend");
							break;
						} else if (outP.equals("2")) {
							JOptionPane.showMessageDialog(this, name1 + " and " + name2 + " are Colleague ");
							break;
						} else if (outP.equals("4")) {
							JOptionPane.showMessageDialog(this, name1 + " and " + name2 + " are Classmate ");
							break;
						}

					}
				if (i == AddRelation.numre) {

					JOptionPane.showMessageDialog(this, "Without this record.");

				}
			}
		} else {
			JOptionPane.showMessageDialog(this, "Error input");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel lb1;
	private javax.swing.JTextField name1;
	private javax.swing.JTextField name2;
	// End of variables declaration//GEN-END:variables
}
